### ISSUE TITLE
I was wondering

### ISSUE THREAD

**Issue by Psychokiller1888** [respeaker/usb_4_mic_array#1]
I know this is coming soon but....

Looking at the picture on the main page, I was wondering if anybody ever thought about the design........

I mean, this is practically not usuable in any sort of builds. Why? Leds and mics are on the same side as the electronics AND the 3.5mm jack as well as the micro usb power in...

How do you want to build this thing in any casing? while having the mics and leds showing outside?

**Comment by xiongyihui** [comment]
This new usb 4 mic array is designed to be compatible with the old usb 6+1 mic array as much as possible. The difference is that microphones reduce to 4 from 7, as the audio processing algorithm is improved. Many of our users are waiting for the new one as the old one is discontinued (its main IC is discontinued by the IC Vendor -_-!)
Anyway, there is a case for the usb 6+1 mic array:

![image](https://user-images.githubusercontent.com/948283/38593641-fc55a26a-3d74-11e8-9700-15075166b5a5.png)

![](https://statics3.seeedstudio.com/seeed/img/2017-01/oUduSND6bGrPUpKjBqj3hofS.jpg)

What kind of mic array is you looking for? We would like to listen your feedback.

**Comment by Psychokiller1888** [comment]
Wow, I don't think you understand what I'm saying, I'm not attacking anything, I even said it's a great product, but mentionned that the placement of the components leave me wondering if it's been thought at all.

Re current draw, the question is as easy as it is: What PSU is needed to fit the respeaker 4? Because obviously the original one, 5.1v 2.5a isn't enough. If I bought a respeaker 4 it is surely not to turn off the leds, I would have bought a microphone hat without leds otherwise...

**Comment by xiongyihui** [comment]
The codec and microphones need about 10 mA. An LED with the max brightness drains about 60 mA at 5V power supply. All the LEDs with the max brightness will need about  12 * 60 = 720 mA.
The brightness control is necessary

**Comment by Psychokiller1888** [comment]
Well, a raspi 3B needs around 700-1000mA. Makes with a respeaker 1730mA
Add to that a 7'' screen about 500mA goes to 2330mA which makes me wondering why using a respeaker on an official PSU (5.1v / 2.5A) goes into undervoltage. Thanks for the reply though!
