### ISSUE TITLE
Audio Output Quality

### ISSUE THREAD

**Issue by MexXxo** [respeaker/usb_4_mic_array#10]
I just received my ReSpeaker Mic Array v2 and the voice recognition is amazing. 
However I noticed that the audio output is very dump / low quality.

I tested the output speaker and cable with my smartphone (same music) and it was better.

Is there somwhere an limit for the audio output quality?

From the output it sounds like 16 KHz or so ...

**Comment by MexXxo** [comment]
Okay I analyzed it a bit further: Yes the Respeaker Mic Array v2 Hardware seems only to support 24-bit 16 KHz as output. For the audio output, to have an acceptable quality 48 KHz would be good, I guess due to UAC 1.0 and DSP Algorithms this has to be limited at some point, but 16 KHz is a really poor output.

**Comment by MexXxo** [comment]
Forum Discussion see https://forum.seeedstudio.com/viewtopic.php?f=91&t=7794

**Comment by KillingJacky** [comment]
Will close this issue as the forum staff has stated the algorithm restriction there.
