### ISSUE TITLE
AECSILENCELEVEL value

### ISSUE THREAD

**Issue by Ali-Amir** [respeaker/usb_4_mic_array#16]
I was wondering if you could explain the value of AECSILENCELEVEL? Comments in the documentation and tuning.py say that the default value is -80dBov, while the actual value is around 1e-8 and the range is in [1e-8, 1].

**Comment by xiongyihui** [comment]
AECSILENCELEVEL is like that the playback will be  considered as silence and be ignored if its level is less than AECSILENCELEVEL.
