### ISSUE TITLE
Alsamixer empty

### ISSUE THREAD

**Issue by jr-k** [respeaker/usb_4_mic_array#27]
I'm trying to adjust capture volume in alsamixer but when I'm choosing this card I got this message : This sound device does not have any controls.

What is a correct asound configuration file for this card ?

Thanks.

**Comment by xiongyihui** [comment]
The device doesn't have any hardware volume controls. We can use the ALSA plugin `softvol` to adjust the volume, or use `tuning.py` to control the gain.

**Comment by jr-k** [comment]
Ok thanks for your answer.
