### ISSUE TITLE
Which license is applied for this repository?

### ISSUE THREAD

**Issue by furushchev** [respeaker/usb_4_mic_array#3]
Hi,

 I'd like to use this nice device and software provided here.
I wonder there is an appropriate license for this project.
If there is, please could you state the license in files? (Or I'll send a pull request if needed)

Thanks in advance!

**Comment by xiongyihui** [comment]
Thanks to point it out. It's the Apache license. Just added a license file.

**Comment by furushchev** [comment]
@xiongyihui Thanks for very quick response! Got it! :+1:
