### ISSUE TITLE
How to check if parameters are updated?

### ISSUE THREAD

**Issue by furushchev** [respeaker/usb_4_mic_array#6]
Hi, 

I'm using Respeaker V2.0 mic array for voice localization.
I use the value of Degree Of Arrival from the device on polling as we can use by `tuning.py`, but since this value has no timestamp, I cannot check this value is updated or not on each polling loop.
Is there any chance to check if the value is updated?

Thank you very much in advance!

**Comment by xiongyihui** [comment]
You need to check the value on a polling loop. Maybe run it on a thread.
