### ISSUE TITLE
can't record audio on win10 when using 1 channel firmware

### ISSUE THREAD

**Issue by wangwei2009** [respeaker/usb_4_mic_array#7]
I update Mic Array v2.0 with 1 channel ASR firmware on ubuntu 16.04 ,and then I can't record audio on win10,but Mic Array itself looks work normal,because it still can do  VAD and DOA.
Is this the bug of the ASR 1 channel firmware,or  just  I bought a broken Mic Array?

**Comment by xiongyihui** [comment]
Are you able to record audio on Ubuntu 16.04?
The Window 10 may need to uninstall the driver of the mic array, and then re-plug the device.

**Comment by wangwei2009** [comment]
Thanks for your quick reply,and this solved my problem!
I uninstalled UAC1.0 driver，re-pluged  Mic Array after restarted my computer,and then everything works fine,Thinks again!
