### ISSUE TITLE
Odas cfg is incorrect

### ISSUE THREAD

**Issue by taospartan** [respeaker/usb_4_mic_array#8]
The microphone layout for use in odas is totally wrong. Results in false doa and separation.

**Comment by xiongyihui** [comment]
@taospartan  Can you explain what is wrong?

**Comment by taospartan** [comment]
If you look at the microphone coordinates they are spaced incorrectly, looks like the mics are positioned in a straight line

Many thanks

**Comment by xiongyihui** [comment]
They are not in a straight line. 


```
        # Microphone 2
        { 
            mu = ( -0.032, +0.000, +0.000 ); 
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 80.0, 100.0 );
        },

        # Microphone 3
        { 
            mu = ( +0.000, -0.032, +0.000 ); 
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 80.0, 100.0 );
        },

        # Microphone 4
        { 
            mu = ( +0.032, +0.000, +0.000 ); 
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 80.0, 100.0 );
        },

        # Microphone 5
        { 
            mu = ( +0.000, +0.032, +0.000 ); 
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 80.0, 100.0 );        
        }
```

**Comment by taospartan** [comment]
My mistake, but they are still not plotting sound sources correctly, this
is my config for the mics see what you think

 mics = (

        # Microphone 2
        {
            mu = ( +0.0239, +0.0239, +0.000 );
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000,
+0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 90.0, 100.0 );
        },

        # Microphone 3
        {
            mu = ( -0.0239, +0.0239, +0.000 );
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000,
+0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 90.0, 100.0 );
        },

        # Microphone 4
        {
            mu = ( -0.0239, -0.0239, +0.000 );
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000,
+0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 90.0, 100.0 );
        },

        # Microphone 5
        {
            mu = ( +0.0239, -0.0239, +0.000 );
            sigma2 = ( +0.000, +0.000, +0.000, +0.000, +0.000, +0.000,
+0.000, +0.000, +0.000 );
            direction = ( +0.000, +0.000, +1.000 );
            angle = ( 90.0, 100.0 );
        }

    );

**Comment by taospartan** [comment]
I understand but unless you do rotate your coords 45 degrees odas does not work as intended especially the tracking . Feel free to test your self

**Comment by xiongyihui** [comment]
I tried your configuration, but didn't see much difference. Maybe it is the difference between `angle = ( 90.0, 100.0 );` and `angle = ( 80.0, 100.0 );  `. Otherwise, it should be a bug.

**Comment by taospartan** [comment]
Ok
